<a href="https://colab.research.google.com/github/Josh1313/-Python_Basics-_1-/blob/main/Clase_6_Pandas_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics 6

# Dataframes de Pandas

Un DataFrame de Python es una tabla de 2-dimensiones, potencialmente hetereogéna y con ejes etiquetados (filas y columnas).

Propiedades de los DataFrames:
  - Columnas pueden ser de distintos tipos de datos
  - modificable de tamaño
  - ejes etiquetados (filas y columnas)
  - se pueden realizar operaciones aritméticas en filas y columnas

Los DataFrames de Pandas consisten básicamente de 3 elementos principales:
-  datos (*data*)
-  filas (*rows*)
-  columnas (*columns*)

![title](https://media.geeksforgeeks.org/wp-content/uploads/finallpandas.png)

### Tipos de datos - dtype( )

Los DataFrames de pandas sostienen los siguientes tipos de datos:


![title](https://pbpython.com/images/pandas_dtypes.png)

## Creación de un DataFrame

In [282]:
import pandas as pd

In [283]:
import pandas as pd

data = {'nombre': ['Juan', 'María', 'Pedro', 'Luisa'],
        'edad': [25, 30, 27, 22],
        'ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla']}

df = pd.DataFrame(data)

print(df)

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    27   Valencia
3  Luisa    22    Sevilla

In [284]:
datos = {'el salvador': ['sonsosnate', 'sonzacate', 'san antonio','nahuizalco'],
         'poblacion' : [20, 50, 300, 45],
         'capital' : ['soso', 'zzz','lll', 'ssss']}

In [285]:
dtt = pd.DataFrame(datos)

In [286]:
dtt

   el salvador  poblacion capital
0   sonsosnate         20    soso
1    sonzacate         50     zzz
2  san antonio        300     lll
3   nahuizalco         45    ssss

In [287]:
import pandas as pd

lista_datos = ['uno', 'dos', 'tres', 'cuatro', 'cinco']

df = pd.DataFrame({'datos': lista_datos})

print(df)

    datos
0     uno
1     dos
2    tres
3  cuatro
4   cinco

In [288]:
lista_nume = [11, 22, 33, 44, 55]

In [289]:
ld = pd.DataFrame({'numeros': lista_nume})

In [290]:
ld

   numeros
0       11
1       22
2       33
3       44
4       55

### DataFrame de una Lista

In [291]:
lista_datos = ['uno','dos','tres','cuatro','cinco']

In [292]:
import pandas as pd

lista_datos = ['uno', 'dos', 'tres', 'cuatro', 'cinco']

df = pd.DataFrame({'datos': lista_datos})

print(df)

    datos
0     uno
1     dos
2    tres
3  cuatro
4   cinco

In [293]:
lista_de_listas = [["Ana",25], ["Yolanda", 35] , ["Eduardo", 14]]

In [294]:
pd.DataFrame(lista_de_listas)

         0   1
0      Ana  25
1  Yolanda  35
2  Eduardo  14

In [295]:
pd.DataFrame?

In [296]:
lista_chips = [["ana",25], ["jose",74], ["castro",85], ["ivone", 35]]

In [297]:
pd.DataFrame(lista_chips)

        0   1
0     ana  25
1    jose  74
2  castro  85
3   ivone  35

#### EJEMPLO - DataFrame 2d - asignar nombre a columnas y etiquetas

In [298]:
lista_de_listas = [['Alex',10],['Berta',12],['Carmen',13]]

columnas = ['nombre', 'edad']

index = ['est. 1', 'est. 2', 'est. 3']

In [299]:
pd.DataFrame(lista_de_listas, index = index, columns = columnas)

        nombre  edad
est. 1    Alex    10
est. 2   Berta    12
est. 3  Carmen    13

In [300]:
pd.DataFrame(lista_de_listas, index = index, columns = columnas)

        nombre  edad
est. 1    Alex    10
est. 2   Berta    12
est. 3  Carmen    13

#### Fijar tipo de datos dtype de un DataFrame

### DataFrame de un Diccionario de listas

In [301]:
diccionario_de_listas = {  "nombres": ['Tomás', 'Elena', 'Juana'] , "edades": [28,34,0]      }

In [302]:
nombre_filas = ["Estudiante 1", "Estudiante 2", "Estudiante 3"]

### DataFrame de una Lista de Diccionarios

In [303]:
lista_dicts = [  {'a': 1, 'b': 2}  ,    {'a': 5, 'b': 10, 'c': 20} ]
lista_dicts

[{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]

In [304]:
pd.DataFrame(lista_dicts)

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [305]:
listo = [{'q': 1, 'w': 2,} , {'a': 3, 'b': 4, 'c': 20}]

In [306]:
pd.DataFrame(listo)

     q    w    a    b     c
0  1.0  2.0  NaN  NaN   NaN
1  NaN  NaN  3.0  4.0  20.0

### Indexar un DataFrame: .index, .columns, .axes

In [307]:
diccionario_gente = {'Nombre':['Tomás', 'Elena', 'Juana', 'Enrique'],'Edad':[28,34,29,42],'Ciudad':['Barcelona',"Tarragona","Lleida","Huesca"], "Hermanos":[1,2,3,0]}

df = pd.DataFrame(diccionario_gente, index = ["Estudiante 1","Estudiante 2","Estudiante 3","Estudiante 4" ])
df

               Nombre  Edad     Ciudad  Hermanos
Estudiante 1    Tomás    28  Barcelona         1
Estudiante 2    Elena    34  Tarragona         2
Estudiante 3    Juana    29     Lleida         3
Estudiante 4  Enrique    42     Huesca         0

In [308]:
df.index

Index(['Estudiante 1', 'Estudiante 2', 'Estudiante 3', 'Estudiante 4'], dtype='object')

In [309]:
df.columns

Index(['Nombre', 'Edad', 'Ciudad', 'Hermanos'], dtype='object')

In [310]:
from os import rename
df.rename

<bound method DataFrame.rename of                Nombre  Edad     Ciudad  Hermanos
Estudiante 1    Tomás    28  Barcelona         1
Estudiante 2    Elena    34  Tarragona         2
Estudiante 3    Juana    29     Lleida         3
Estudiante 4  Enrique    42     Huesca         0>

#### Probemos el método Rename para sustituir nombres

In [311]:
df

               Nombre  Edad     Ciudad  Hermanos
Estudiante 1    Tomás    28  Barcelona         1
Estudiante 2    Elena    34  Tarragona         2
Estudiante 3    Juana    29     Lleida         3
Estudiante 4  Enrique    42     Huesca         0

In [312]:
df.rename({'ciudad' : 'pais'})

               Nombre  Edad     Ciudad  Hermanos
Estudiante 1    Tomás    28  Barcelona         1
Estudiante 2    Elena    34  Tarragona         2
Estudiante 3    Juana    29     Lleida         3
Estudiante 4  Enrique    42     Huesca         0

In [313]:
df.rename({'Edad' : 'color'}, axis =  1, inplace = True)

In [314]:
df

               Nombre  color     Ciudad  Hermanos
Estudiante 1    Tomás     28  Barcelona         1
Estudiante 2    Elena     34  Tarragona         2
Estudiante 3    Juana     29     Lleida         3
Estudiante 4  Enrique     42     Huesca         0

## Exploración de DataFrames

### Atributos de un DataFrame

|df.attribute|Descripción|
|----|----|
|**dtypes**| lista todos los tipos de datos de las columnas del dataframe |
|**columns**| lista el nombre de las columnas |
|**axes**| lista las etiquetas de las filas y nombres de las columnas |
|**ndim**| nº de dimensiones del dataframe|
|**size**| nº de elementos del dataframe|
|**shape**| devuelve  una tupla que representa la dimensionalidad del df, (*filas*x*columnas*)|
|**values**| representación NumPy de los datos|

In [315]:
d = {'uno' : pd.Series([10, 12, 3], index=['fila1', 'fila2', 'fila3']),
   'two' : pd.Series([15.0, 2.0, 4.0], index=['fila1', 'fila2', 'fila3'])}

In [316]:
df = pd.DataFrame(d)

In [317]:
df

       uno   two
fila1   10  15.0
fila2   12   2.0
fila3    3   4.0

In [318]:
df.dtypes

uno      int64
two    float64
dtype: object

In [319]:
df.columns

Index(['uno', 'two'], dtype='object')

In [320]:
df.axes

[Index(['fila1', 'fila2', 'fila3'], dtype='object'),
 Index(['uno', 'two'], dtype='object')]

In [321]:
df.ndim

2

In [322]:
df.size

6

In [323]:
df.shape

(3, 2)

In [324]:
df.values

array([[10., 15.],
       [12.,  2.],
       [ 3.,  4.]])

### Métodos de un DataFrame

|df.**method()**|Descripción|
|----|----|
|**info()**| información básica del df
|**head(n)**| lista las primeras *n* filas |
|**tail(n)**| lista las últimas *n* filas |
|**describe()**| genera algunas métricas estadísticas descriptivas del dataframe, sólo para columnas numérics |
|**max()**| devuelve el valor máximo de cada columna numérica |
|**min()**| devuelve el valor mínimo de cada columna numérica |
|**std()**| devuelve la desviación estándar de cada columna numérica |
|**sample(n)**| devuelve un set aleatorio del dataframe |

In [325]:
diccionario_gente = {

    'Nombre':['Tomás', 'Elena', 'Juana', 'Enrique'],
    'Edad':[28,34,29,42],
    'Ciudad':['Barcelona',"Tarragona",2,"Huesca"],
    "Hermanos":[1,2,3,0]


}
diccionario_gente

{'Nombre': ['Tomás', 'Elena', 'Juana', 'Enrique'],
 'Edad': [28, 34, 29, 42],
 'Ciudad': ['Barcelona', 'Tarragona', 2, 'Huesca'],
 'Hermanos': [1, 2, 3, 0]}

In [326]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, fila1 to fila3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   uno     3 non-null      int64
 1   two     3 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 72.0+ bytes

In [327]:
df.head()

       uno   two
fila1   10  15.0
fila2   12   2.0
fila3    3   4.0

In [328]:
df.tail()

       uno   two
fila1   10  15.0
fila2   12   2.0
fila3    3   4.0

In [329]:
df.describe(include = 'all')

             uno   two
count   3.000000   3.0
mean    8.333333   7.0
std     4.725816   7.0
min     3.000000   2.0
25%     6.500000   3.0
50%    10.000000   4.0
75%    11.000000   9.5
max    12.000000  15.0

In [330]:
df.max()

uno    12.0
two    15.0
dtype: float64

In [331]:
df.min()

uno    3.0
two    2.0
dtype: float64

In [332]:
df.std()

uno    4.725816
two    7.000000
dtype: float64

In [333]:
df.sample()

       uno  two
fila3    3  4.0

Ejercicio: Genera un df del diccionario anterior y asígnale como indice de filas "Estudiante 1", "Estudiante 2", etc, y aplica cada uno de los métodos de la tabla anterior. Comentemos resultados.

In [334]:
import pandas as pd

datos = {'Nombre': ['Ana', 'Beto', 'Carlos', 'Diana', 'Elena'],
         'Edad': [22, 21, 23, 22, 24],
         'Sexo': ['F', 'M', 'M', 'F', 'F'],
         'Carrera': ['Ing. Civil', 'Ing. Electrónica', 'Ing. Industrial', 'Ing. Civil', 'Ing. Química'],
         'Promedio': [9.0, 8.5, 8.7, 9.2, 8.8]}

df = pd.DataFrame(datos, index=['Estudiante 1', 'Estudiante 2', 'Estudiante 3', 'Estudiante 4', 'Estudiante 5'])

# Mostrar el dataframe
print(df)

# Obtener estadísticas básicas del dataframe
print(df.describe())

# Obtener la media del promedio
print("Media del promedio:", df["Promedio"].mean())

# Obtener el estudiante con el promedio más alto
estudiante_max_promedio = df.loc[df["Promedio"].idxmax()]
print("Estudiante con el promedio más alto:", estudiante_max_promedio["Nombre"])

# Obtener el número de estudiantes por carrera
num_estudiantes_carrera = df["Carrera"].value_counts()
print("Número de estudiantes por carrera:\n", num_estudiantes_carrera)

              Nombre  Edad Sexo           Carrera  Promedio
Estudiante 1     Ana    22    F        Ing. Civil       9.0
Estudiante 2    Beto    21    M  Ing. Electrónica       8.5
Estudiante 3  Carlos    23    M   Ing. Industrial       8.7
Estudiante 4   Diana    22    F        Ing. Civil       9.2
Estudiante 5   Elena    24    F      Ing. Química       8.8
            Edad  Promedio
count   5.000000  5.000000
mean   22.400000  8.840000
std     1.140175  0.270185
min    21.000000  8.500000
25%    22.000000  8.700000
50%    22.000000  8.800000
75%    23.000000  9.000000
max    24.000000  9.200000
Media del promedio: 8.84
Estudiante con el promedio más alto: Diana
Número de estudiantes por carrera:
 Ing. Civil          2
Ing. Electrónica    1
Ing. Industrial     1
Ing. Química        1
Name: Carrera, dtype: int64

### Trasponer el DataFrame - .T

In [335]:
df.T

,Estudiante 1,Estudiante 2,Estudiante 3,Estudiante 4,Estudiante 5
Nombre,Ana,Beto,Carlos,Diana,Elena
Edad,22,21,23,22,24
Sexo,F,M,M,F,F
Carrera,Ing. Civil,Ing. Electrónica,Ing. Industrial,Ing. Civil,Ing. Química
Promedio,9.0,8.5,8.7,9.2,8.8

In [336]:
df.head()

              Nombre  Edad Sexo           Carrera  Promedio
Estudiante 1     Ana    22    F        Ing. Civil       9.0
Estudiante 2    Beto    21    M  Ing. Electrónica       8.5
Estudiante 3  Carlos    23    M   Ing. Industrial       8.7
Estudiante 4   Diana    22    F        Ing. Civil       9.2
Estudiante 5   Elena    24    F      Ing. Química       8.8

### Ordenar DataFrame - sort_index(), sort_values()

In [337]:
dic_coches = {'Marca': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Precio': [22000,25000,27000,35000],
        'Año': [2015,2013,2018,2018]
        }
df = pd.DataFrame(dic_coches)
df

            Marca  Precio   Año
0     Honda Civic   22000  2015
1  Toyota Corolla   25000  2013
2      Ford Focus   27000  2018
3         Audi A4   35000  2018

In [338]:
df.sort_index()

            Marca  Precio   Año
0     Honda Civic   22000  2015
1  Toyota Corolla   25000  2013
2      Ford Focus   27000  2018
3         Audi A4   35000  2018

In [339]:
df.sort_index(axis = 1)

    Año           Marca  Precio
0  2015     Honda Civic   22000
1  2013  Toyota Corolla   25000
2  2018      Ford Focus   27000
3  2018         Audi A4   35000

In [340]:
df.sort_index(axis = 'columns')

    Año           Marca  Precio
0  2015     Honda Civic   22000
1  2013  Toyota Corolla   25000
2  2018      Ford Focus   27000
3  2018         Audi A4   35000

In [341]:
df.sort_index(axis = 'columns', ascending = False)

   Precio           Marca   Año
0   22000     Honda Civic  2015
1   25000  Toyota Corolla  2013
2   27000      Ford Focus  2018
3   35000         Audi A4  2018

In [342]:
df.sort_index(axis = 'columns', ascending = False, inplace = True)

In [343]:
df

   Precio           Marca   Año
0   22000     Honda Civic  2015
1   25000  Toyota Corolla  2013
2   27000      Ford Focus  2018
3   35000         Audi A4  2018

In [344]:
df.sort_values(by = 'Marca', ascending = False)

   Precio           Marca   Año
1   25000  Toyota Corolla  2013
0   22000     Honda Civic  2015
2   27000      Ford Focus  2018
3   35000         Audi A4  2018

In [345]:
df.sort_values(by = ['Marca','Precio'], ascending = False)

   Precio           Marca   Año
1   25000  Toyota Corolla  2013
0   22000     Honda Civic  2015
2   27000      Ford Focus  2018
3   35000         Audi A4  2018

##### Ejercicio:

- Crea un DataFrame con el diccionario siguiente y ordena según:
- Nombre de columnas en orden descendente.
- Index en orden ascendente.
- Por values utilizando las columnas Año, Precio y Marca de mayor a menor

In [346]:
dic_coches = {'Marca': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Precio': [22000,25000,27000,35000],
        'Año': [2015,2013,2018,2018]
        }

In [347]:
import pandas as pd

dic_coches = {'Marca': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
              'Precio': [22000,25000,27000,35000],
              'Año': [2015,2013,2018,2018]}

df_coches = pd.DataFrame(dic_coches)

print("DataFrame original:")
print(df_coches)

# Ordenar columnas en orden descendente
df_coches = df_coches[sorted(df_coches.columns, reverse=True)]
print("DataFrame ordenado por columnas en orden descendente:")
print(df_coches)

# Ordenar filas en orden ascendente
df_coches = df_coches.sort_index()
print("DataFrame ordenado por filas en orden ascendente:")
print(df_coches)

# Ordenar por valores utilizando las columnas Año, Precio y Marca de mayor a menor
df_coches = df_coches.sort_values(['Año', 'Precio', 'Marca'], ascending=[False, False, False])
print("DataFrame ordenado por valores de Año, Precio y Marca de mayor a menor:")
print(df_coches)

DataFrame original:
            Marca  Precio   Año
0     Honda Civic   22000  2015
1  Toyota Corolla   25000  2013
2      Ford Focus   27000  2018
3         Audi A4   35000  2018
DataFrame ordenado por columnas en orden descendente:
   Precio           Marca   Año
0   22000     Honda Civic  2015
1   25000  Toyota Corolla  2013
2   27000      Ford Focus  2018
3   35000         Audi A4  2018
DataFrame ordenado por filas en orden ascendente:
   Precio           Marca   Año
0   22000     Honda Civic  2015
1   25000  Toyota Corolla  2013
2   27000      Ford Focus  2018
3   35000         Audi A4  2018
DataFrame ordenado por valores de Año, Precio y Marca de mayor a menor:
   Precio           Marca   Año
3   35000         Audi A4  2018
2   27000      Ford Focus  2018
0   22000     Honda Civic  2015
1   25000  Toyota Corolla  2013

In [348]:
df.sort_index(axis = 'columns', ascending = False)

   Precio           Marca   Año
0   22000     Honda Civic  2015
1   25000  Toyota Corolla  2013
2   27000      Ford Focus  2018
3   35000         Audi A4  2018

In [349]:
df.sort_index(axis = 0, ascending = True)

   Precio           Marca   Año
0   22000     Honda Civic  2015
1   25000  Toyota Corolla  2013
2   27000      Ford Focus  2018
3   35000         Audi A4  2018

In [350]:
df.sort_values(by = ['Año', 'Precio', 'Marca'], ascending = False)

   Precio           Marca   Año
3   35000         Audi A4  2018
2   27000      Ford Focus  2018
0   22000     Honda Civic  2015
1   25000  Toyota Corolla  2013

## Missing Data

### Borrar filas con missing data - .dropna( )

In [351]:
dic_coches = {'Marca': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Precio': [22000,25000,27000, None],
        'Año': [2015,2013, None,2018]
        }

In [352]:
df = pd.DataFrame(dic_coches)
df

            Marca   Precio     Año
0     Honda Civic  22000.0  2015.0
1  Toyota Corolla  25000.0  2013.0
2      Ford Focus  27000.0     NaN
3         Audi A4      NaN  2018.0

In [353]:
df.dropna()

            Marca   Precio     Año
0     Honda Civic  22000.0  2015.0
1  Toyota Corolla  25000.0  2013.0

In [354]:
df.dropna(axis = 'columns')

            Marca
0     Honda Civic
1  Toyota Corolla
2      Ford Focus
3         Audi A4

In [355]:
df_n = pd.DataFrame(df, columns = ['Marca', 'precio', 'Año', 1, 2])

In [356]:
df_n

            Marca  precio     Año   1   2
0     Honda Civic     NaN  2015.0 NaN NaN
1  Toyota Corolla     NaN  2013.0 NaN NaN
2      Ford Focus     NaN     NaN NaN NaN
3         Audi A4     NaN  2018.0 NaN NaN

In [357]:
df_n.dropna(how = 'all')

            Marca  precio     Año   1   2
0     Honda Civic     NaN  2015.0 NaN NaN
1  Toyota Corolla     NaN  2013.0 NaN NaN
2      Ford Focus     NaN     NaN NaN NaN
3         Audi A4     NaN  2018.0 NaN NaN

In [358]:
df_n.dropna(axis = 'columns', how = 'all')

            Marca     Año
0     Honda Civic  2015.0
1  Toyota Corolla  2013.0
2      Ford Focus     NaN
3         Audi A4  2018.0

In [359]:
df_n.dropna(how = 'any')

Empty DataFrame
Columns: [Marca, precio, Año, 1, 2]
Index: []

In [360]:
df_n.dropna(thresh = 3)

Empty DataFrame
Columns: [Marca, precio, Año, 1, 2]
Index: []

In [361]:
df_n.dropna(subset = ["Año"])

            Marca  precio     Año   1   2
0     Honda Civic     NaN  2015.0 NaN NaN
1  Toyota Corolla     NaN  2013.0 NaN NaN
3         Audi A4     NaN  2018.0 NaN NaN

### Rellena NaN valores - .fillna( )

In [362]:
df_n

            Marca  precio     Año   1   2
0     Honda Civic     NaN  2015.0 NaN NaN
1  Toyota Corolla     NaN  2013.0 NaN NaN
2      Ford Focus     NaN     NaN NaN NaN
3         Audi A4     NaN  2018.0 NaN NaN

In [363]:
df_n['Año'].fillna(value = 5)

0    2015.0
1    2013.0
2       5.0
3    2018.0
Name: Año, dtype: float64

In [364]:
df_n['Año'].fillna(value = df_n['Año'].mean())

0    2015.000000
1    2013.000000
2    2015.333333
3    2018.000000
Name: Año, dtype: float64

In [365]:
round(df_n['Año'].fillna(value = df_n['Año'].mean()))

0    2015.0
1    2013.0
2    2015.0
3    2018.0
Name: Año, dtype: float64

In [366]:
df_o = df_n['Año'].fillna(value = df_n['Año'].mean())

In [367]:
df_o.astype('int')

0    2015
1    2013
2    2015
3    2018
Name: Año, dtype: int64

In [368]:
df_n['Año'].fillna(value = df['Año'].median(), inplace = True)

In [369]:
df_n

            Marca  precio     Año   1   2
0     Honda Civic     NaN  2015.0 NaN NaN
1  Toyota Corolla     NaN  2013.0 NaN NaN
2      Ford Focus     NaN  2015.0 NaN NaN
3         Audi A4     NaN  2018.0 NaN NaN

In [370]:
df_n["Año"]

0    2015.0
1    2013.0
2    2015.0
3    2018.0
Name: Año, dtype: float64

### Check dónde hay NaN - .isna( )

In [371]:
df_n.isna().sum()

Marca     0
precio    4
Año       0
1         4
2         4
dtype: int64

In [372]:
df_n.count()

Marca     4
precio    0
Año       4
1         0
2         0
dtype: int64

### Eliminar duplicados - drop_duplicates()

In [373]:
x = pd.DataFrame([[1, 2, 2, 4], [1, 2, 2, 4], [1, 2, 5, 3]])
x

   0  1  2  3
0  1  2  2  4
1  1  2  2  4
2  1  2  5  3

In [374]:
x.drop_duplicates()

   0  1  2  3
0  1  2  2  4
2  1  2  5  3

In [375]:
x.drop_duplicates(keep = False)

   0  1  2  3
2  1  2  5  3

In [376]:
x.drop_duplicates(subset = [0, 1])

   0  1  2  3
0  1  2  2  4

In [377]:
x.drop_duplicates(subset = [0, 1], keep = False)

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [378]:
x

   0  1  2  3
0  1  2  2  4
1  1  2  2  4
2  1  2  5  3

## Subset DataFrames

- .loc: selecciona una fila/columna mediante su nombre
- .iloc: selecciona una fila/columna mediante su índice
- .at: selecciona un único elemento mediante su nombre
- .iat: selecciona un único elemento mediante su índice

### Selección de Columnas

In [379]:
dic_coches = {'Marca': ['Honda','Toyota','Ford'],
        'Precio': [22000,25000,27000],
        'Año': [2015,2013,2018]
        }
df = pd.DataFrame(dic_coches)
df.index = ["Laura","Lorenzo","Arnau"]
df

          Marca  Precio   Año
Laura     Honda   22000  2015
Lorenzo  Toyota   25000  2013
Arnau      Ford   27000  2018

In [380]:
df['Marca']

Laura       Honda
Lorenzo    Toyota
Arnau        Ford
Name: Marca, dtype: object

In [381]:
df[['Marca', 'Precio']]

          Marca  Precio
Laura     Honda   22000
Lorenzo  Toyota   25000
Arnau      Ford   27000

### Selección de Filas

Existen dos métodos para seleccionar filas de un DataFrame:
- **.loc()** - **loc**aliza por el nombre
- **.iloc()** - **loc**aliza por **í**ndice numérico

![title](https://www.w3resource.com/w3r_images/pandas-series-iloc-image-3.svg)

In [382]:
df

          Marca  Precio   Año
Laura     Honda   22000  2015
Lorenzo  Toyota   25000  2013
Arnau      Ford   27000  2018

In [383]:
df.loc['Lorenzo'] = 2300

In [384]:
df

         Marca  Precio   Año
Laura    Honda   22000  2015
Lorenzo   2300    2300  2300
Arnau     Ford   27000  2018

In [385]:
df.iloc[1]

Marca     2300
Precio    2300
Año       2300
Name: Lorenzo, dtype: object

In [386]:
df.loc['Lorenzo', 'Precio']

2300

In [387]:
df.iloc[1,1]

2300

In [388]:
df.loc[df['Año'] < 2020, 'Año']= 2010

In [389]:
df

         Marca  Precio   Año
Laura    Honda   22000  2010
Lorenzo   2300    2300  2300
Arnau     Ford   27000  2010

### Selecciona un elemento - .at( ), .iat( )

![title](https://www.w3resource.com/w3r_images/pandas-series-iat-image-2.svg)

In [390]:
df

         Marca  Precio   Año
Laura    Honda   22000  2010
Lorenzo   2300    2300  2300
Arnau     Ford   27000  2010

In [391]:
df.at['Laura', 'Marca']

'Honda'

Ejercicio:
- Del siguiente DataFrame realiza lo siguiente:
- Genera un nuevo DataFrame de Marca y Precio.
- Genera una serie Año.
- Selecciona la fila Arnau
- Selecciona las dos últimas filas.

In [392]:
dic_coches = {'Marca': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4', 'Seat Leon'],
        'Precio': [22000,25000,27000,35000,17000],
        'Año': [2015,2013,2018,2018,2017]
        }
df = pd.DataFrame(dic_coches)
df.index = ["Laura","Lorenzo","Arnau","Guillem","Guille"]
df

                  Marca  Precio   Año
Laura       Honda Civic   22000  2015
Lorenzo  Toyota Corolla   25000  2013
Arnau        Ford Focus   27000  2018
Guillem         Audi A4   35000  2018
Guille        Seat Leon   17000  2017

In [393]:
df[['Marca', 'Precio']]

                  Marca  Precio
Laura       Honda Civic   22000
Lorenzo  Toyota Corolla   25000
Arnau        Ford Focus   27000
Guillem         Audi A4   35000
Guille        Seat Leon   17000

In [394]:
df['Año']

Laura      2015
Lorenzo    2013
Arnau      2018
Guillem    2018
Guille     2017
Name: Año, dtype: int64

In [395]:
df.loc['Arnau']

Marca     Ford Focus
Precio         27000
Año             2018
Name: Arnau, dtype: object

In [396]:
df.iloc[-2:]

             Marca  Precio   Año
Guillem    Audi A4   35000  2018
Guille   Seat Leon   17000  2017

### Selección condicional de filas

In [397]:
df

                  Marca  Precio   Año
Laura       Honda Civic   22000  2015
Lorenzo  Toyota Corolla   25000  2013
Arnau        Ford Focus   27000  2018
Guillem         Audi A4   35000  2018
Guille        Seat Leon   17000  2017

In [398]:
df.loc[ : , "Marca" ]

Laura         Honda Civic
Lorenzo    Toyota Corolla
Arnau          Ford Focus
Guillem           Audi A4
Guille          Seat Leon
Name: Marca, dtype: object

In [399]:
df[ df["Marca"] == 2018]

Empty DataFrame
Columns: [Marca, Precio, Año]
Index: []

In [400]:
df.query('Marca == 2018')

Empty DataFrame
Columns: [Marca, Precio, Año]
Index: []

In [401]:
df.query(" Precio > 25000")

              Marca  Precio   Año
Arnau    Ford Focus   27000  2018
Guillem     Audi A4   35000  2018

#### Filtrar por múltiples condiciones

In [402]:
df[(df["Precio"] > 2500) & (df["Año"] == 2018)]

              Marca  Precio   Año
Arnau    Ford Focus   27000  2018
Guillem     Audi A4   35000  2018

In [403]:
df.query("Precio > 25000 and Año == 2018")

              Marca  Precio   Año
Arnau    Ford Focus   27000  2018
Guillem     Audi A4   35000  2018

In [404]:
df[df["Marca"].str.contains("Honda")]

             Marca  Precio   Año
Laura  Honda Civic   22000  2015

In [405]:
resultado = df.query('Año >= 2015')

In [406]:
resultado

               Marca  Precio   Año
Laura    Honda Civic   22000  2015
Arnau     Ford Focus   27000  2018
Guillem      Audi A4   35000  2018
Guille     Seat Leon   17000  2017

Ejercicio:
- Del siguiente DataFrame realiza lo siguiente:
- Genera un nuevo DataFrame con los Precios menores a 30000 y año mayor a 2013.
- Genera un nuevo DataFrame donde se cumpla que el año es 2018 ó el Precio es menor a 20000.
- Genera un nuevo DataFrame donde Año sea solo 2013 ò 2018.

In [407]:
dic_coches = {'Marca': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4', 'Seat Leon'],
        'Precio': [22000,25000,27000,35000,17000],
        'Año': [2015,2013,2018,2018,2017]
        }
df = pd.DataFrame(dic_coches)
df.index = ["Laura","Lorenzo","Arnau","Guillem","Guille"]
df

                  Marca  Precio   Año
Laura       Honda Civic   22000  2015
Lorenzo  Toyota Corolla   25000  2013
Arnau        Ford Focus   27000  2018
Guillem         Audi A4   35000  2018
Guille        Seat Leon   17000  2017

In [408]:
Precios_menores = pd.DataFrame(df["Precio"])

In [409]:
Precios_menores

         Precio
Laura     22000
Lorenzo   25000
Arnau     27000
Guillem   35000
Guille    17000

In [410]:
df.query("Precio < 30000 and Año > 2013" )

              Marca  Precio   Año
Laura   Honda Civic   22000  2015
Arnau    Ford Focus   27000  2018
Guille    Seat Leon   17000  2017

In [411]:
df.query("Precio == 2018 or Precio < 20000")

            Marca  Precio   Año
Guille  Seat Leon   17000  2017

In [412]:
df.query("Precio == 2013 or Año == 2017")

            Marca  Precio   Año
Guille  Seat Leon   17000  2017

In [413]:
df.query('Año == 2013 or Año ==2017 ')

                  Marca  Precio   Año
Lorenzo  Toyota Corolla   25000  2013
Guille        Seat Leon   17000  2017

In [414]:
df.query("Año.isin([2013,2017])")

                  Marca  Precio   Año
Lorenzo  Toyota Corolla   25000  2013
Guille        Seat Leon   17000  2017

## Setting de un DataFrame

In [415]:
df

                  Marca  Precio   Año
Laura       Honda Civic   22000  2015
Lorenzo  Toyota Corolla   25000  2013
Arnau        Ford Focus   27000  2018
Guillem         Audi A4   35000  2018
Guille        Seat Leon   17000  2017

In [416]:
df['Precio']

Laura      22000
Lorenzo    25000
Arnau      27000
Guillem    35000
Guille     17000
Name: Precio, dtype: int64

In [417]:
df.query("Precio == 2700")["Precio"] = 30000

### Añadir columnas

In [418]:
df

                  Marca  Precio   Año
Laura       Honda Civic   22000  2015
Lorenzo  Toyota Corolla   25000  2013
Arnau        Ford Focus   27000  2018
Guillem         Audi A4   35000  2018
Guille        Seat Leon   17000  2017

In [419]:
df.loc[df["Precio"]  == 27000, "Precio"] = 30000

In [420]:
df

                  Marca  Precio   Año
Laura       Honda Civic   22000  2015
Lorenzo  Toyota Corolla   25000  2013
Arnau        Ford Focus   30000  2018
Guillem         Audi A4   35000  2018
Guille        Seat Leon   17000  2017

In [421]:
df.loc[df["Precio"]  == 27000, "Precio"] = 30000

In [422]:
#below anadir

In [423]:
df["color"] =['amarillo', ' rojo', ' verde', 'rojo', 'amarillo']

In [424]:
df

                  Marca  Precio   Año     color
Laura       Honda Civic   22000  2015  amarillo
Lorenzo  Toyota Corolla   25000  2013      rojo
Arnau        Ford Focus   30000  2018     verde
Guillem         Audi A4   35000  2018      rojo
Guille        Seat Leon   17000  2017  amarillo

In [425]:
df['pvp'] = df['Precio'] *1.21

In [426]:
df

                  Marca  Precio   Año     color      pvp
Laura       Honda Civic   22000  2015  amarillo  26620.0
Lorenzo  Toyota Corolla   25000  2013      rojo  30250.0
Arnau        Ford Focus   30000  2018     verde  36300.0
Guillem         Audi A4   35000  2018      rojo  42350.0
Guille        Seat Leon   17000  2017  amarillo  20570.0

In [427]:
df['suma'] = df['Precio'] + df['Año']

In [428]:
df

                  Marca  Precio   Año     color      pvp   suma
Laura       Honda Civic   22000  2015  amarillo  26620.0  24015
Lorenzo  Toyota Corolla   25000  2013      rojo  30250.0  27013
Arnau        Ford Focus   30000  2018     verde  36300.0  32018
Guillem         Audi A4   35000  2018      rojo  42350.0  37018
Guille        Seat Leon   17000  2017  amarillo  20570.0  19017

In [429]:
df['menores de 25000'] = df['Precio'] < 27000

In [430]:
df

,Marca,Precio,Año,color,pvp,suma,menores de 25000
Laura,Honda Civic,22000,2015,amarillo,26620.0,24015,True
Lorenzo,Toyota Corolla,25000,2013,rojo,30250.0,27013,True
Arnau,Ford Focus,30000,2018,verde,36300.0,32018,False
Guillem,Audi A4,35000,2018,rojo,42350.0,37018,False
Guille,Seat Leon,17000,2017,amarillo,20570.0,19017,True

In [431]:
df['menores de 25000'] = (df['Precio'] < 27000).astype('int')

In [432]:
df

,Marca,Precio,Año,color,pvp,suma,menores de 25000
Laura,Honda Civic,22000,2015,amarillo,26620.0,24015,1
Lorenzo,Toyota Corolla,25000,2013,rojo,30250.0,27013,1
Arnau,Ford Focus,30000,2018,verde,36300.0,32018,0
Guillem,Audi A4,35000,2018,rojo,42350.0,37018,0
Guille,Seat Leon,17000,2017,amarillo,20570.0,19017,1

### Drop columnas - .pop( )

In [433]:
df

,Marca,Precio,Año,color,pvp,suma,menores de 25000
Laura,Honda Civic,22000,2015,amarillo,26620.0,24015,1
Lorenzo,Toyota Corolla,25000,2013,rojo,30250.0,27013,1
Arnau,Ford Focus,30000,2018,verde,36300.0,32018,0
Guillem,Audi A4,35000,2018,rojo,42350.0,37018,0
Guille,Seat Leon,17000,2017,amarillo,20570.0,19017,1

In [434]:
df.pop('suma')

Laura      24015
Lorenzo    27013
Arnau      32018
Guillem    37018
Guille     19017
Name: suma, dtype: int64

### Eliminar filas - .drop( )

In [435]:
df

                  Marca  Precio   Año     color      pvp  menores de 25000
Laura       Honda Civic   22000  2015  amarillo  26620.0                 1
Lorenzo  Toyota Corolla   25000  2013      rojo  30250.0                 1
Arnau        Ford Focus   30000  2018     verde  36300.0                 0
Guillem         Audi A4   35000  2018      rojo  42350.0                 0
Guille        Seat Leon   17000  2017  amarillo  20570.0                 1

In [436]:
df.drop(columns = "pvp")

                  Marca  Precio   Año     color  menores de 25000
Laura       Honda Civic   22000  2015  amarillo                 1
Lorenzo  Toyota Corolla   25000  2013      rojo                 1
Arnau        Ford Focus   30000  2018     verde                 0
Guillem         Audi A4   35000  2018      rojo                 0
Guille        Seat Leon   17000  2017  amarillo                 1

In [437]:
df.drop(index = "Arnau")

                  Marca  Precio   Año     color      pvp  menores de 25000
Laura       Honda Civic   22000  2015  amarillo  26620.0                 1
Lorenzo  Toyota Corolla   25000  2013      rojo  30250.0                 1
Guillem         Audi A4   35000  2018      rojo  42350.0                 0
Guille        Seat Leon   17000  2017  amarillo  20570.0                 1

In [438]:
df.drop(index = ["Arnau", "Laura"], inplace = True)

In [439]:
df

                  Marca  Precio   Año     color      pvp  menores de 25000
Lorenzo  Toyota Corolla   25000  2013      rojo  30250.0                 1
Guillem         Audi A4   35000  2018      rojo  42350.0                 0
Guille        Seat Leon   17000  2017  amarillo  20570.0                 1

In [440]:
import numpy as np

In [441]:
df.reset_index().drop(index = np.arange(2), inplace = True)

## Concatenar DataFrames -.append( ), -concat( )

### Anexionar filas - .append( )

In [442]:
d = {'columna 1' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'columna 2' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

   columna 1  columna 2
a        1.0          1
b        2.0          2
c        3.0          3
d        NaN          4

In [443]:
df.append(df)

<ipython-input-443-8ddd54bd77dd>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df)

   columna 1  columna 2
a        1.0          1
b        2.0          2
c        3.0          3
d        NaN          4
a        1.0          1
b        2.0          2
c        3.0          3
d        NaN          4

In [444]:
nueva_fila = [[1,2]]

In [445]:
f = pd.DataFrame(nueva_fila)
f

   0  1
0  1  2

In [446]:
df.append(f )

<ipython-input-446-3310ea9ff7b6>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(f )

   columna 1  columna 2    0    1
a        1.0        1.0  NaN  NaN
b        2.0        2.0  NaN  NaN
c        3.0        3.0  NaN  NaN
d        NaN        4.0  NaN  NaN
0        NaN        NaN  1.0  2.0

### Concantenar - .concat( )

In [447]:
import numpy as np

In [448]:
df = pd.DataFrame(np.random.randn(10, 4))
df

          0         1         2         3
0  1.287496  0.049968  0.167226  0.324615
1 -1.242027 -0.223197  0.594812  0.196966
2 -1.233663 -1.116210 -1.040948 -0.414033
3  0.490263 -0.308178  0.058038 -0.870845
4  0.554961 -0.719676 -1.134508 -0.517885
5 -1.320302  0.958556 -1.099469 -1.040729
6 -0.657823  0.070347 -0.941483  0.764670
7 -1.063833  0.159384 -1.708186  0.157634
8 -0.475530 -0.004876 -0.338467  0.734760
9 -1.448439  0.072179 -0.329576 -1.223685

In [449]:
df.shape

(10, 4)

In [450]:
df2 = pd.DataFrame(np.random.randn(2, 2))
df2

          0         1
0 -0.655361 -0.996373
1  1.589765 -0.714397

In [451]:
df2.shape

(2, 2)

In [452]:
horizontal_stack = pd.concat([df,df2],axis=0)
horizontal_stack

          0         1         2         3
0  1.287496  0.049968  0.167226  0.324615
1 -1.242027 -0.223197  0.594812  0.196966
2 -1.233663 -1.116210 -1.040948 -0.414033
3  0.490263 -0.308178  0.058038 -0.870845
4  0.554961 -0.719676 -1.134508 -0.517885
5 -1.320302  0.958556 -1.099469 -1.040729
6 -0.657823  0.070347 -0.941483  0.764670
7 -1.063833  0.159384 -1.708186  0.157634
8 -0.475530 -0.004876 -0.338467  0.734760
9 -1.448439  0.072179 -0.329576 -1.223685
0 -0.655361 -0.996373       NaN       NaN
1  1.589765 -0.714397       NaN       NaN

#### EJEMPLO: Concatenar en axis=1

In [453]:
vertical_stack = pd.concat([df,df2],axis=1)
vertical_stack

          0         1         2         3         0         1
0  1.287496  0.049968  0.167226  0.324615 -0.655361 -0.996373
1 -1.242027 -0.223197  0.594812  0.196966  1.589765 -0.714397
2 -1.233663 -1.116210 -1.040948 -0.414033       NaN       NaN
3  0.490263 -0.308178  0.058038 -0.870845       NaN       NaN
4  0.554961 -0.719676 -1.134508 -0.517885       NaN       NaN
5 -1.320302  0.958556 -1.099469 -1.040729       NaN       NaN
6 -0.657823  0.070347 -0.941483  0.764670       NaN       NaN
7 -1.063833  0.159384 -1.708186  0.157634       NaN       NaN
8 -0.475530 -0.004876 -0.338467  0.734760       NaN       NaN
9 -1.448439  0.072179 -0.329576 -1.223685       NaN       NaN

In [454]:
df2

          0         1
0 -0.655361 -0.996373
1  1.589765 -0.714397

In [455]:
pd.concat([df,df2],axis=1, join='outer')

          0         1         2         3         0         1
0  1.287496  0.049968  0.167226  0.324615 -0.655361 -0.996373
1 -1.242027 -0.223197  0.594812  0.196966  1.589765 -0.714397
2 -1.233663 -1.116210 -1.040948 -0.414033       NaN       NaN
3  0.490263 -0.308178  0.058038 -0.870845       NaN       NaN
4  0.554961 -0.719676 -1.134508 -0.517885       NaN       NaN
5 -1.320302  0.958556 -1.099469 -1.040729       NaN       NaN
6 -0.657823  0.070347 -0.941483  0.764670       NaN       NaN
7 -1.063833  0.159384 -1.708186  0.157634       NaN       NaN
8 -0.475530 -0.004876 -0.338467  0.734760       NaN       NaN
9 -1.448439  0.072179 -0.329576 -1.223685       NaN       NaN

In [456]:
pd.concat([df,df2],axis=1, join='inner' , ignore_index = True)

          0         1         2         3         4         5
0  1.287496  0.049968  0.167226  0.324615 -0.655361 -0.996373
1 -1.242027 -0.223197  0.594812  0.196966  1.589765 -0.714397

## Merge DataFrames- .merge( )

En Pandas existen **4 tipos de joins**

![image.png]()

In [457]:
compra_1={'elementos':[1,2,3,4,5],'categorias':['vegetal','vegetal','fruta','vegetal','fruta'],'nombres':['zanahoria','coliflor','manzana','patata','uvas']}
a = pd.DataFrame(compra_1, columns=['elementos','categorias','nombres'])
a

   elementos categorias    nombres
0          1    vegetal  zanahoria
1          2    vegetal   coliflor
2          3      fruta    manzana
3          4    vegetal     patata
4          5      fruta       uvas

Creamos DataFrame **b**

In [458]:
compra_2={'elementos':[4,5,6,7,8],'categorias':['vegetal','fruta','fruta','vegetal','fruta'],'nombres':['brócoli','mango','pera','guisantes','sandía']}
b = pd.DataFrame(compra_2, columns=['elementos','categorias','nombres'])
b

   elementos categorias    nombres
0          4    vegetal    brócoli
1          5      fruta      mango
2          6      fruta       pera
3          7    vegetal  guisantes
4          8      fruta     sandía

Creamos DataFrame **c**

In [459]:
compra_3={'elementos':[1,2,3,4,5,6,7,8,9,10],'precio':[12,23,98,15,88,24,67,58,26,96]}
c = pd.DataFrame(compra_3, columns=['elementos','precio'])
c

   elementos  precio
0          1      12
1          2      23
2          3      98
3          4      15
4          5      88
5          6      24
6          7      67
7          8      58
8          9      26
9         10      96

In [460]:
pd.merge(a, c, left_on = "elementos", right_on = "elementos", how = "outer")

   elementos categorias    nombres  precio
0          1    vegetal  zanahoria      12
1          2    vegetal   coliflor      23
2          3      fruta    manzana      98
3          4    vegetal     patata      15
4          5      fruta       uvas      88
5          6        NaN        NaN      24
6          7        NaN        NaN      67
7          8        NaN        NaN      58
8          9        NaN        NaN      26
9         10        NaN        NaN      96

In [461]:
# se puede cambiar el how

In [462]:
pd.merge(a, c, left_index = True, right_on = 'elementos', how = 'inner')

   elementos  elementos_x categorias   nombres  elementos_y  precio
0          1            2    vegetal  coliflor            1      12
1          2            3      fruta   manzana            2      23
2          3            4    vegetal    patata            3      98
3          4            5      fruta      uvas            4      15

In [463]:
a.merge(c)

   elementos categorias    nombres  precio
0          1    vegetal  zanahoria      12
1          2    vegetal   coliflor      23
2          3      fruta    manzana      98
3          4    vegetal     patata      15
4          5      fruta       uvas      88

## Join vía indices - .join( )

In [464]:
A1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],'B': ['B0', 'B1', 'B2']},index=['K0', 'K1', 'K2'])

In [465]:
A1

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [466]:
A2 = pd.DataFrame({'C': ['C0', 'C1', 'C2'], 'D': ['D0', 'D1', 'D2']},index=['K0', 'K2', 'K3'])

In [467]:
A2

     C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2

In [468]:
A3 = A1.join(A2)
A3

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

## Grouping

In [469]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar','foo', 'bar', 'foo', 'foo'],'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],'C': np.random.randn(8),'D': np.random.randn(8)})
df

     A      B         C         D
0  foo    one -1.125736 -1.609142
1  bar    one  0.150904 -2.129192
2  foo    two  0.572941 -0.716926
3  bar  three  0.299766 -0.598012
4  foo    two -0.043692 -0.446300
5  bar    two -0.174645  1.750661
6  foo    one  0.757600  1.425757
7  foo  three -1.616196  0.600227

Funciones de agregación sobre columnas numéricas

### Group by a varios niveles

In [470]:
df.groupby('A').sum()

<ipython-input-470-180a798bba5b>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('A').sum()

            C         D
A
bar  0.276026 -0.976544
foo -1.455083 -0.746384

In [471]:
df.groupby(['A', 'B']).mean()

                  C         D
A   B
bar one    0.150904 -2.129192
    three  0.299766 -0.598012
    two   -0.174645  1.750661
foo one   -0.184068 -0.091693
    three -1.616196  0.600227
    two    0.264625 -0.581613

In [472]:
df.groupby(['A', 'B']).agg(['sum', 'mean', 'last'])

                  C                             D
                sum      mean      last       sum      mean      last
A   B
bar one    0.150904  0.150904  0.150904 -2.129192 -2.129192 -2.129192
    three  0.299766  0.299766  0.299766 -0.598012 -0.598012 -0.598012
    two   -0.174645 -0.174645 -0.174645  1.750661  1.750661  1.750661
foo one   -0.368136 -0.184068  0.757600 -0.183386 -0.091693  1.425757
    three -1.616196 -1.616196 -1.616196  0.600227  0.600227  0.600227
    two    0.529249  0.264625 -0.043692 -1.163225 -0.581613 -0.446300

### Detalle de funciones de agregación o agrupación

|Función|Descripción|
|----|:------|
|mean()|Calcula la media del grupo|
|sum()|Calcula la suma del grupo de valores |
|size()|Calcula el tamaño del grupo|
|count()|Calcula el contador del grupo|
|std()|Calcula la desviación estandar del grupo|
|var()|Calcula la varianza del grupo|
|sem()|Calcula el error estandar del grupo|
|describe()|Genera estadística descriptiva|
|first()|Devuelve el primer elemento del grupo|
|last()|Devuelve el último elemento del grupo|
|nth()|Coge el *n*th elemento del grupo|
|min()|Calcula el valor mínimo del grupo|
|max()|Cacula el valor máximo del grupo|

### Aplicar múltiples funciones

##### Ejercicio:
- En el siguiente DataFrame, agrupar valores según la columna A y obtener de las siguientes columnas el máximo, la media, la suma y el último valor.

In [473]:
df = pd.DataFrame({'A': ['a', 'b', 'a', 'c','b', 'b', 'a', 'a'],'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],'C': np.random.randn(8),'D': np.random.randn(8)})
df

   A      B         C         D
0  a    one  0.680960 -1.067589
1  b    one  1.026664 -0.532053
2  a    two  0.477166  0.844467
3  c  three  1.435863 -1.103578
4  b    two  1.077007  0.775923
5  b    two  1.816670  0.010756
6  a    one -0.573246  0.348980
7  a  three -0.096947  0.050357

In [474]:
df.describe()

              C         D
count  8.000000  8.000000
mean   0.730517 -0.084092
std    0.787050  0.758171
min   -0.573246 -1.103578
25%    0.333638 -0.665937
50%    0.853812  0.030556
75%    1.166721  0.455716
max    1.816670  0.844467

In [475]:
df.groupby('A').agg(['max', 'mean', 'sum', 'last'])

<ipython-input-475-509f2374833c>:1: FutureWarning: ['B'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby('A').agg(['max', 'mean', 'sum', 'last'])

          C                                       D                      \
        max      mean       sum      last       max      mean       sum
A
a  0.680960  0.121983  0.487933 -0.096947  0.844467  0.044054  0.176215
b  1.816670  1.306781  3.920342  1.816670  0.775923  0.084876  0.254627
c  1.435863  1.435863  1.435863  1.435863 -1.103578 -1.103578 -1.103578


       last
A
a  0.050357
b  0.010756
c -1.103578

## Pivot Table

In [476]:
# Tabla pivote para calcular el promedio de la columna 'C' para cada combinación única de 'A' y 'B'
pivot_table1 = pd.pivot_table(df, values='C', index=['A', 'B'], aggfunc=np.mean)

print(pivot_table1)

                C
A B
a one    0.053857
  three -0.096947
  two    0.477166
b one    1.026664
  two    1.446839
c three  1.435863

In [477]:
# Tabla pivote para calcular la suma de la columna 'D' para cada valor único en la columna 'A'
pivot_table2 = pd.pivot_table(df, values='D', index='A', aggfunc=np.sum)

print(pivot_table2)

          D
A
a  0.176215
b  0.254627
c -1.103578

In [478]:
# Tabla pivote para calcular el máximo y el mínimo de la columna 'C' para cada valor único en la columna 'B'
pivot_table3 = pd.pivot_table(df, values='C', index='B', aggfunc=[np.max, np.min])

print(pivot_table3)

           amax      amin
              C         C
B
one    1.026664 -0.573246
three  1.435863 -0.096947
two    1.816670  0.477166

# RESUMEN de métodos sobre DataFrames

## Métodos matemáticos

|Función|Description|
|:---|:---|
|add()|Method is used to add series or list like objects with same length to the caller series|
|sub()|Method is used to subtract series or list like objects with same length from the caller series|
|mul()|Method is used to multiply series or list like objects with same length with the caller series|
|div()|Method is used to divide series or list like objects with same length by the caller series|
|sum()|Returns the sum of the values for the requested axis|
|prod()|Returns the product of the values for the requested axis|
|mean()|Returns the mean of the values for the requested axis|
|pow()|Method is used to put each element of passed series as exponential power of caller series and returned the results
|abs()|Method is used to get the absolute numeric value of each element in Series/DataFrame||
|cov()|Method is used to find covariance of two series|

## Métodos exploratorios

<style> table {display: block} </style>
|Función|Descripción|
|---|------|
|combine_first()|Method is used to combine two series into one|
|count()|Returns number of non-NA/null observations in the Series|
|size()|Returns the number of elements in the underlying data|
|name()|Method allows to give a name to a Series object, i.e. to the column|
|is_unique()|Method returns boolean if values in the object are unique|
|idxmax()|Method to extract the index positions of the highest values in a Series|
|idxmin()|Method to extract the index positions of the lowest values in a Series|
|sort_values()|Method is called on a Series to sort the values in ascending or descending order|
|sort_index()|Method is called on a pandas Series to sort it by the index instead of its values|
|head()|Method is used to return a specified number of rows from the beginning of a Series. The method returns a brand new Series|
|tail()|Method is used to return a specified number of rows from the end of a Series. The method returns a brand new Series|
|le()|Used to compare every element of Caller series with passed series.It returns True for every element which is Less than or Equal to the element in passed series|
|ne()|Used to compare every element of Caller series with passed series. It returns True for every element which is Not Equal to the element in passed series|
|ge()|Used to compare every element of Caller series with passed series. It returns True for every element which is Greater than or Equal to the element in passed series|
|eq()|Used to compare every element of Caller series with passed series. It returns True for every element which is Equal to the element in passed series|
|gt()|Used to compare two series and return Boolean value for every respective element|
|lt()|Used to compare two series and return Boolean value for every respective element|
|clip()|Used to clip value below and above to passed Least and Max value|
|clip_lower()|Used to clip values below a passed least value|
|clip_upper()|Used to clip values above a passed maximum value|
|astype()|Method is used to change data type of a series|
|tolist()|Method is used to convert a series to list|
|get()|Method is called on a Series to extract values from a Series. This is alternative syntax to the traditional bracket syntax|
|unique()|Pandas unique() is used to see the unique values in a particular column|
|nunique()|Pandas nunique() is used to get a count of unique values|
|value_counts()|Method to count the number of the times each unique value occurs in a Series|
|factorize()|Method helps to get the numeric representation of an array by identifying distinct values|
|map()|Method to tie together the values from one object to another|
|between()|Pandas between() method is used on series to check which values lie between first and second argument|
|apply()|Method is called and feeded a Python function as an argument to use the function on every Series value. This method is helpful for executing custom operations that are not included in pandas or numpy|

El fichero titanic.csv contiene información sobre los pasajeros del Titanic.

Escribir un programa con los siguientes requisitos:

- Generar un DataFrame con los datos del fichero. Para importar usaremos Pandas.
- Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas y filas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas
- Mostrar por pantalla los datos del pasajero con identificador 148.
- Mostrar por pantalla los nombres de las personas que iban en primera clase ordenadas alfabéticamente.
- Mostrar por pantalla el porcentaje de personas que sobrevivieron y murieron.
- Mostrar por pantalla el porcentaje de personas que sobrevivieron en cada clase.
- Eliminar del DataFrame los pasajeros con edad desconocida.
- Mostrar por pantalla la edad media de las mujeres que viajaban en cada clase.
- Añadir una nueva columna booleana para ver si el pasajero era menor de edad o no.
- Mostrar por pantalla el porcentaje de menores y mayores de edad que sobrevivieron en cada clase.

In [480]:
import pandas as pd
import numpy as np

In [481]:
from google.colab import drive
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [482]:
url = "https://github.com/charleskot/data_science_program/blob/d5403319ceeca80dbd536831145339b21af00e89/titanic.csv?raw=true"

In [483]:
df = pd.read_csv(url)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Generar un DataFrame con los datos del fichero. Para importar usaremos Pandas.
Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas y filas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas

In [484]:
print("Dimensiones del DataFrame:", df.shape)
print("Número de datos en el DataFrame:", df.size)
print("Nombres de las columnas:", df.columns.tolist())
print("Nombres de las filas (índice):", df.index.tolist())
print("Tipos de datos de las columnas:")
print(df.dtypes)
print("Las 10 primeras filas:")
print(df.head(10))
print("Las 10 últimas filas:")
print(df.tail(10))

Dimensiones del DataFrame: (891, 12)
Número de datos en el DataFrame: 10692
Nombres de las columnas: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
Nombres de las filas (índice): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890]
Tipos de datos de las columnas:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
Las 10 primeras filas:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C
Las 10 últimas filas:
     PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann
882          883         0       3              Dahlberg, Miss. Gerda Ulrika
883          884         0       2             Banfield, Mr. Frederick James
884          885         0       3                    Sutehall, Mr. Henry Jr
885          886         0       3      Rice, Mrs. William (Margaret Norton)
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
881    male  33.0      0      0            349257   7.8958   NaN        S
882  female  22.0      0      0              7552  10.5167   NaN        S
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
885  female  39.0      0      5            382652  29.1250   NaN        Q
886    male  27.0      0      0            211536  13.0000   NaN        S
887  female  19.0      0      0            112053  30.0000   B42        S
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
889    male  26.0      0      0            111369  30.0000  C148        C
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [485]:
#Mostrar por pantalla los datos del pasajero con identificador 148.

In [486]:
print("Datos del pasajero con identificador 148:")
print(df.loc[147])

Datos del pasajero con identificador 148:
PassengerId                                 148
Survived                                      0
Pclass                                        3
Name           Ford, Miss. Robina Maggie "Ruby"
Sex                                      female
Age                                         9.0
SibSp                                         2
Parch                                         2
Ticket                               W./C. 6608
Fare                                     34.375
Cabin                                       NaN
Embarked                                      S
Name: 147, dtype: object

In [487]:
# Paso 4: Mostrar los nombres de las personas que iban en primera clase ordenadas alfabéticamente
print("Nombres de las personas que iban en primera clase ordenados alfabéticamente:")
print(df[df['Pclass'] == 1]['Name'].sort_values())

Nombres de las personas que iban en primera clase ordenados alfabéticamente:
730                      Allen, Miss. Elisabeth Walton
305                     Allison, Master. Hudson Trevor
297                       Allison, Miss. Helen Loraine
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
460                                Anderson, Mr. Harry
                            ...
155                        Williams, Mr. Charles Duane
351             Williams-Lambert, Mr. Fletcher Fellows
55                                   Woolner, Mr. Hugh
555                                 Wright, Mr. George
325                           Young, Miss. Marie Grice
Name: Name, Length: 216, dtype: object

In [488]:
# Paso 5: Mostrar el porcentaje de personas que sobrevivieron y murieron
sobrevivieron = df[df['Survived'] == 1].shape[0]
murieron = df[df['Survived'] == 0].shape[0]
total_pasajeros = df.shape[0]
porcentaje_sobrevivieron = (sobrevivieron / total_pasajeros) * 100
porcentaje_murieron = (murieron / total_pasajeros) * 100

print("Porcentaje de personas que sobrevivieron: {:.2f}%".format(porcentaje_sobrevivieron))
print("Porcentaje de personas que murieron: {:.2f}%".format(porcentaje_murieron))

Porcentaje de personas que sobrevivieron: 38.38%
Porcentaje de personas que murieron: 61.62%

In [489]:
# Paso 6: Mostrar el porcentaje de personas que sobrevivieron en cada clase
porcentaje_sobrevivieron_clase = df.groupby('Pclass')['Survived'].mean() * 100
print("Porcentaje de personas que sobrevivieron en cada clase:")
print(porcentaje_sobrevivieron_clase)

Porcentaje de personas que sobrevivieron en cada clase:
Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [490]:
# Paso 7: Eliminar del DataFrame los pasajeros con edad desconocida
df = df.dropna(subset=['Age'])

In [491]:
# Paso 8: Mostrar la edad media de las mujeres que viajaban en cada clase
edad_media_mujeres_clase = df[df['Sex'] == 'female'].groupby('Pclass')['Age'].mean()
print("Edad media de las mujeres que viajaban en cada clase:")
print(edad_media_mujeres_clase)

Edad media de las mujeres que viajaban en cada clase:
Pclass
1    34.611765
2    28.722973
3    21.750000
Name: Age, dtype: float64

In [ ]:
# Paso 9: Añadir una nueva columna booleana para ver si el pasajero era menor de edad o no
df['MenorEdad'] = df['Age'] < 18

In [493]:
# Paso 10: Mostrar el porcentaje de menores y mayores de edad que sobrevivieron en cada clase
porcentaje_sobrevivieron_menores_clase = df[df['MenorEdad'] == True].groupby('Pclass')['Survived'].mean() * 100
porcentaje_sobrevivieron_mayores_clase = df[df['MenorEdad'] == False].groupby('Pclass')['Survived'].mean() * 100

print("Porcentaje de menores de edad que sobrevivieron en cada clase:")
print(porcentaje_sobrevivieron_menores_clase)

print("Porcentaje de mayores de edad que sobrevivieron en cada clase:")
print(porcentaje_sobrevivieron_mayores_clase)

Porcentaje de menores de edad que sobrevivieron en cada clase:
Pclass
1    91.666667
2    91.304348
3    37.179487
Name: Survived, dtype: float64
Porcentaje de mayores de edad que sobrevivieron en cada clase:
Pclass
1    63.793103
2    41.333333
3    20.216606
Name: Survived, dtype: float64